# Generated by Django 2.2.5 on 2019-09-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190916_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_length',
            field=models.IntegerField(null=True),
        ),
    ]
