# Generated by Django 2.2.5 on 2019-09-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_lesson_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='published',
            new_name='posted',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='year',
            new_name='year_written',
        ),
    ]
