# Generated by Django 2.2.5 on 2019-10-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191005_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='files',
            field=models.FileField(default='1', upload_to='courses/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
