# Generated by Django 2.2.5 on 2019-09-17 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190917_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='org',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='org',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
