# Generated by Django 2.2.5 on 2019-10-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191005_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(default=30, null=True),
        ),
    ]
