# Generated by Django 2.2.5 on 2019-10-08 11:23

import CanterburyTales.courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191005_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='files',
            field=models.FileField(upload_to=CanterburyTales.courses.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=CanterburyTales.courses.models.user_directory_path)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
