# Generated by Django 2.2.5 on 2019-09-18 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190917_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='authors',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CanterburyTales.courses.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audience',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
