# Generated by Django 2.2.5 on 2019-10-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20191008_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='files',
        ),
    ]
