# Generated by Django 2.2.5 on 2019-10-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='upvotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvotes', to='profiles.Profile'),
        ),
    ]
