# Generated by Django 2.2.5 on 2019-09-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190917_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='posted',
            field=models.DateField(null=True),
        ),
    ]
