# Generated by Django 2.2.5 on 2019-10-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20191009_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to='profiles.Profile'),
        ),
    ]
