# Generated by Django 2.2.5 on 2019-09-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190919_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvotes', to='CanterburyTales.courses.Profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='year_written',
            field=models.IntegerField(default=2019),
        ),
    ]
