# Generated by Django 2.2.5 on 2019-09-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190924_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='upvotes',
            field=models.ManyToManyField(default=0, related_name='upvotes', to='CanterburyTales.courses.Profile'),
        ),
    ]
