# Generated by Django 2.2.5 on 2019-10-19 15:50

import CanterburyTales.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191005_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[CanterburyTales.profiles.models.file_size]),
        ),
    ]
